# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from cg_mrslam/Edge.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Edge(genpy.Message):
  _md5sum = "384fe2e5bedbc35780991580d2e3ab00"
  _type = "cg_mrslam/Edge"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """int32 idFrom
int32 idTo
float64[3] estimate
float64[6] information"""
  __slots__ = ['idFrom','idTo','estimate','information']
  _slot_types = ['int32','int32','float64[3]','float64[6]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       idFrom,idTo,estimate,information

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Edge, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.idFrom is None:
        self.idFrom = 0
      if self.idTo is None:
        self.idTo = 0
      if self.estimate is None:
        self.estimate = [0.,0.,0.]
      if self.information is None:
        self.information = [0.,0.,0.,0.,0.,0.]
    else:
      self.idFrom = 0
      self.idTo = 0
      self.estimate = [0.,0.,0.]
      self.information = [0.,0.,0.,0.,0.,0.]

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_2i.pack(_x.idFrom, _x.idTo))
      buff.write(_struct_3d.pack(*self.estimate))
      buff.write(_struct_6d.pack(*self.information))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 8
      (_x.idFrom, _x.idTo,) = _struct_2i.unpack(str[start:end])
      start = end
      end += 24
      self.estimate = _struct_3d.unpack(str[start:end])
      start = end
      end += 48
      self.information = _struct_6d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_2i.pack(_x.idFrom, _x.idTo))
      buff.write(self.estimate.tostring())
      buff.write(self.information.tostring())
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 8
      (_x.idFrom, _x.idTo,) = _struct_2i.unpack(str[start:end])
      start = end
      end += 24
      self.estimate = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=3)
      start = end
      end += 48
      self.information = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=6)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_6d = struct.Struct("<6d")
_struct_2i = struct.Struct("<2i")
_struct_3d = struct.Struct("<3d")
