// Generated by gencpp from file cg_mrslam/Ping.msg
// DO NOT EDIT!


#ifndef CG_MRSLAM_MESSAGE_PING_H
#define CG_MRSLAM_MESSAGE_PING_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace cg_mrslam
{
template <class ContainerAllocator>
struct Ping_
{
  typedef Ping_<ContainerAllocator> Type;

  Ping_()
    : header()
    , robotFrom(0)
    , robotTo(0)  {
    }
  Ping_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , robotFrom(0)
    , robotTo(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int32_t _robotFrom_type;
  _robotFrom_type robotFrom;

   typedef int32_t _robotTo_type;
  _robotTo_type robotTo;




  typedef boost::shared_ptr< ::cg_mrslam::Ping_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cg_mrslam::Ping_<ContainerAllocator> const> ConstPtr;

}; // struct Ping_

typedef ::cg_mrslam::Ping_<std::allocator<void> > Ping;

typedef boost::shared_ptr< ::cg_mrslam::Ping > PingPtr;
typedef boost::shared_ptr< ::cg_mrslam::Ping const> PingConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cg_mrslam::Ping_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cg_mrslam::Ping_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace cg_mrslam

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'cg_mrslam': ['/home/liby3/catkin_ws_lby/src/cg_mrslam/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::cg_mrslam::Ping_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cg_mrslam::Ping_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cg_mrslam::Ping_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cg_mrslam::Ping_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cg_mrslam::Ping_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cg_mrslam::Ping_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cg_mrslam::Ping_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dbb8c06e269de6d27aacbfe820c1a146";
  }

  static const char* value(const ::cg_mrslam::Ping_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdbb8c06e269de6d2ULL;
  static const uint64_t static_value2 = 0x7aacbfe820c1a146ULL;
};

template<class ContainerAllocator>
struct DataType< ::cg_mrslam::Ping_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cg_mrslam/Ping";
  }

  static const char* value(const ::cg_mrslam::Ping_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cg_mrslam::Ping_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
int32 robotFrom\n\
int32 robotTo\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::cg_mrslam::Ping_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cg_mrslam::Ping_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.robotFrom);
      stream.next(m.robotTo);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Ping_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cg_mrslam::Ping_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cg_mrslam::Ping_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "robotFrom: ";
    Printer<int32_t>::stream(s, indent + "  ", v.robotFrom);
    s << indent << "robotTo: ";
    Printer<int32_t>::stream(s, indent + "  ", v.robotTo);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CG_MRSLAM_MESSAGE_PING_H
