// Generated by gencpp from file cg_mrslam/VSE2.msg
// DO NOT EDIT!


#ifndef CG_MRSLAM_MESSAGE_VSE2_H
#define CG_MRSLAM_MESSAGE_VSE2_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cg_mrslam
{
template <class ContainerAllocator>
struct VSE2_
{
  typedef VSE2_<ContainerAllocator> Type;

  VSE2_()
    : id(0)
    , estimate()  {
      estimate.assign(0.0);
  }
  VSE2_(const ContainerAllocator& _alloc)
    : id(0)
    , estimate()  {
  (void)_alloc;
      estimate.assign(0.0);
  }



   typedef int32_t _id_type;
  _id_type id;

   typedef boost::array<double, 3>  _estimate_type;
  _estimate_type estimate;




  typedef boost::shared_ptr< ::cg_mrslam::VSE2_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cg_mrslam::VSE2_<ContainerAllocator> const> ConstPtr;

}; // struct VSE2_

typedef ::cg_mrslam::VSE2_<std::allocator<void> > VSE2;

typedef boost::shared_ptr< ::cg_mrslam::VSE2 > VSE2Ptr;
typedef boost::shared_ptr< ::cg_mrslam::VSE2 const> VSE2ConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cg_mrslam::VSE2_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cg_mrslam::VSE2_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace cg_mrslam

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'cg_mrslam': ['/home/liby3/catkin_ws_lby/src/cg_mrslam/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::cg_mrslam::VSE2_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cg_mrslam::VSE2_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cg_mrslam::VSE2_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cg_mrslam::VSE2_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cg_mrslam::VSE2_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cg_mrslam::VSE2_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cg_mrslam::VSE2_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4e742a0df2817c655a3ca88a845b4f80";
  }

  static const char* value(const ::cg_mrslam::VSE2_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4e742a0df2817c65ULL;
  static const uint64_t static_value2 = 0x5a3ca88a845b4f80ULL;
};

template<class ContainerAllocator>
struct DataType< ::cg_mrslam::VSE2_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cg_mrslam/VSE2";
  }

  static const char* value(const ::cg_mrslam::VSE2_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cg_mrslam::VSE2_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 id\n\
float64[3] estimate\n\
";
  }

  static const char* value(const ::cg_mrslam::VSE2_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cg_mrslam::VSE2_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.estimate);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VSE2_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cg_mrslam::VSE2_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cg_mrslam::VSE2_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.id);
    s << indent << "estimate[]" << std::endl;
    for (size_t i = 0; i < v.estimate.size(); ++i)
    {
      s << indent << "  estimate[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.estimate[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // CG_MRSLAM_MESSAGE_VSE2_H
