// Generated by gencpp from file ndn_ros/info.msg
// DO NOT EDIT!


#ifndef NDN_ROS_MESSAGE_INFO_H
#define NDN_ROS_MESSAGE_INFO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ndn_ros
{
template <class ContainerAllocator>
struct info_
{
  typedef info_<ContainerAllocator> Type;

  info_()
    : testInfo()  {
    }
  info_(const ContainerAllocator& _alloc)
    : testInfo(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _testInfo_type;
  _testInfo_type testInfo;




  typedef boost::shared_ptr< ::ndn_ros::info_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ndn_ros::info_<ContainerAllocator> const> ConstPtr;

}; // struct info_

typedef ::ndn_ros::info_<std::allocator<void> > info;

typedef boost::shared_ptr< ::ndn_ros::info > infoPtr;
typedef boost::shared_ptr< ::ndn_ros::info const> infoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ndn_ros::info_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ndn_ros::info_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ndn_ros

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'ndn_ros': ['/home/liby3/catkin_ws_lby/src/ndn_ros/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ndn_ros::info_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ndn_ros::info_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ndn_ros::info_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ndn_ros::info_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ndn_ros::info_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ndn_ros::info_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ndn_ros::info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dd28e0abe28786cbb9432df03a243809";
  }

  static const char* value(const ::ndn_ros::info_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdd28e0abe28786cbULL;
  static const uint64_t static_value2 = 0xb9432df03a243809ULL;
};

template<class ContainerAllocator>
struct DataType< ::ndn_ros::info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ndn_ros/info";
  }

  static const char* value(const ::ndn_ros::info_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ndn_ros::info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string testInfo\n\
";
  }

  static const char* value(const ::ndn_ros::info_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ndn_ros::info_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.testInfo);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct info_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ndn_ros::info_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ndn_ros::info_<ContainerAllocator>& v)
  {
    s << indent << "testInfo: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.testInfo);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NDN_ROS_MESSAGE_INFO_H
